SOHU_PLATFORM = 'sohu'
KUAIBAO_PLATFORM = 'kuaibao'
UC_PLATFORM = 'uczzd'
TAOBAO_PLATFORM = 'taobao'

SOURCE_LIST = (
    SOHU_PLATFORM,
    KUAIBAO_PLATFORM,
    UC_PLATFORM,
    TAOBAO_PLATFORM
)

API_SOURCE_LIST = (
    UC_PLATFORM,
)

TITLE_SIMILARITY_SWITCH = True

TITLE_SIMILARITY_THRESHOLD = 0.4

MATCH_RISE_KEYWORD_SWITCH = True