history = (
    # "http://mp.sohu.com/profile?xpt=OTg4MzM4NTkzMDkxMTM3NTM2QHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=bTE1MDI3NjA1NjI2QHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=cHBhZzA2MDFiM2E5YWVmOUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MTAwNTc5MDg0NDk3NDA0NzIzMkBzb2h1LmNvbQ==",
    # "http://mp.sohu.com/profile?xpt=aHhoemxAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=MTAxOTUxMzI0MTIwMzg0MzA3MkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=c29odW1wcmZwMWRwQHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=ODIwODMzODU3QHFxLmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzI5OTU5NzUzZjE4NkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzMxMDU5N2NmMjNlNkBzb2h1LmNvbQ==",
    # "http://mp.sohu.com/profile?xpt=dHRjZ183OTg5ODVAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=OTkwMTY1MTc4MDMxMTMyNjcyQHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=Y2hlbmdyMTc3OEBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=Y2Jzal8xMzUyNjhAc29odS5jb20=",
    # "http://mp.sohu.com/profile?xpt=bWluZ3VvbGlzaGlAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=QTY4MkIzNjQ3NTFCOEIxQ0Y0MUQ3NTEyQ0IwN0IwNkVAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=Z2FmanJvbG9yeEBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MTIzMDE4NjA4MkBzaW5hLnNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=OTgwODE1NjQ3MDQwODg0NzM2QHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=cHBhZzMzMzFjZWI4YjhiZEBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzIxMDk5ZmNmN2YxNUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MjYwMjIyMjJFNTlFMjE5ODY5RDU1NzdFMUY4OUFENTdAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzM5MzMwNTAzMDgyMUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=b1NlSFRzX1Rnb0dCblpJTlUzeTFWeEp2UWVzY0B3ZWNoYXQuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzg1MjYwMjRkZTJhNUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzI2MjMzYWI3MzUwOUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MjczODk0MTIwMDhBRDQxMEE4OTRBMzk0Q0Y4QUE0RkFAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzU3MTIwZjc2OWEwOEBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=aG9jcWJ0d2dnbUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MTAzNzcwNjY4OTExOTMxODAxNkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=NTkyNDM4NjYwQHFxLmNvbQ==",
    "http://mp.sohu.com/profile?xpt=c29odW1wZm41bW0wQHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=aW5lZWRob3VzZUAxMjYuY29t",
    "http://mp.sohu.com/profile?xpt=c29odXptdGNoZ3QybGZAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzQwODNlZmQ2ZmExMkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MTAzMzU2NTI1ODA3NTMzMjYwOEBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=OTE4MDk1OTFGRjg1NEU1REU3MUU4RjAxMkNGOTk5NzFAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=emRtdWh5bXpjYUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=OTczODczOTA3Mzg1ODc2NDgwQHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=cHBhZzMyMDFiMWQ4NzI5Y0Bzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzA2MTYwZDNkOTgwNkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=NjEwNDkzQThDMkVDMTA3Q0I2NjcwOTc4MDdEMEYwOUVAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=MTc0MTc5NDMxMEBzaW5hLnNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=OTczMzY4NzU1QHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=OTBjaGVud2VuQDE2My5jb20=",
    "http://mp.sohu.com/profile?xpt=amhoenRAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=YW5ra3lqYWRlQHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=cHBhZzY1MTQzNGEwY2Q1N0Bzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=REIzRUVCQzg0OTRGREVFOENFOTEwMjhDRUNDMDI3QTNAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=NDEzNUNBODk2MUE0OEU0Qzk2NjQ3NzU1RDRGNzQxM0RAcXEuc29odS5jb20=",
)


animation = (
    "http://mp.sohu.com/profile?xpt=c29odXptdHZ0cDlwanBAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzgxMThkZmU3YTVmNUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=c29odXptdDRreGdvZXlAc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzcwNDNkNzlkZmM0ZkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=NENFNkIxQUExOEYzQjJENjA4QzA1MEUzNDFERDEyNDNAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzUzODJjNGNlMTFkNUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=REEyMTJGMzNDMTk3NzU0MTUwNTI3MDQ2OEZGRTg1MzhAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=YWlvbHlhQHNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=ZW1vbnNlZUAxNjMuY29t",
    "http://mp.sohu.com/profile?xpt=cHBhZzkzNDNhMzYxNDlhOUBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=QkRFQkIyNDVEOTgxOTlFNUJFMEVFMTcyNURGMDA0QTRAcXEuc29odS5jb20=",
    "http://mp.sohu.com/profile?xpt=cHBhZzAxNjg0YTg5ZTM1ZkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzI5MjUyYzNiNjczNkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=cHBhZzI3MzA1NzZhZDMxMkBzb2h1LmNvbQ==",
    "http://mp.sohu.com/profile?xpt=MzIwOTM3MTQyNUBzaW5hLnNvaHUuY29t",
    "http://mp.sohu.com/profile?xpt=OTcxNjYwNTA4MTg3MDIxMzEyQHNvaHUuY29t",
)